### ISSUE TITLE
error with 20-clients lab

### ISSUE THREAD

**Issue by scranton** [RedHatWorkshops/amqv7-workshop#4]
after completing lab 10-configure-broker, you've removed all of the acceptors except for 61616. 20-clients lab depends on a running broker with ability to connect to `amqp://localhost:5672`

May want to add instructions to reset broker from lab 10 to add back in that port OR add instructions to change example to reference port 61616

**Comment by christian-posta** [comment]
Yah, the instruction is in there, but it is quite hidden. I've added a more explicit instruction.
